# Generated by Django 5.0.1 on 2024-10-04 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="quizsets",
            fields=[
                (
                    "set_number",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("topic", models.CharField(max_length=50)),
                ("question_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(null=True)),
                ("answer", models.CharField(max_length=1)),
                ("A", models.CharField(max_length=255)),
                ("B", models.CharField(max_length=255)),
                ("C", models.CharField(max_length=255)),
                ("D", models.CharField(max_length=255)),
                (
                    "quiz_set",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="Discord_admin.quizsets",
                    ),
                ),
            ],
        ),
    ]
