# Generated by Django 5.0.1 on 2024-10-03 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Discord_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="quiz_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="Discord_admin.quizsets",
            ),
        ),
    ]
