# Generated by Django 5.0.1 on 2024-10-07 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Discord_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="resposnes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("answer", models.CharField(max_length=100)),
                ("time", models.IntegerField()),
                ("score", models.IntegerField()),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="Discord_admin.quizsets",
                    ),
                ),
            ],
        ),
    ]
