# Generated by Django 5.0.1 on 2024-10-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Discord_admin", "0002_resposnes"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsets",
            name="answer_key",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
